# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Jason Tang
email: 1999jasontang@gmail.com
description: My home page
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
github_username:  MildlySpicy
linkedin_username: 1999jasontang
color: 75FF3A


# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed

# defaults:
#   -
#     scope:
#       path: "assets/img" # Empty string means defaults apply to all files
#     values:
#       image: True
        

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/


# What I do
# Aside from academia, I take pleasure in learning programming languages through side projects, such as this website. To see more of my projects, check out my <a href="https://www.github.com/MildlySpicy" style="color:#00B0FF" target="_blank">Github</a>.

# I also work part time as a private tutor to help somewhat alleviate the immense student debt I have. If you're curious here's the company's <a href="https://www.goodstudytutoring.com" style="color:#00B0FF" target="_blank">site</a>.